### ISSUE TITLE
puppetize firewall rules

### ISSUE THREAD

**Issue by davidschober** [nulib/images#139]

**Comment by Toputnal** [comment]
Firewall rules on which servers?

**Comment by davidschober** [comment]
Images-p
Images-s
Menu-s
Menu-p

**Comment by davidschober** [comment]
@Toputnal this is a duplicate correct? All firewall rules are take care of, documented, and automated if possible? If so, go ahead and close.

**Comment by Toputnal** [comment]
This is actually a bigger deal.  Currently, we don't have puppet controlling firewall rules in the production environment.  The firewall rules in place on managed-hosting servers have all been put in place by hand by NUIT.  David and I need to reverse engineer the setup of the servers and very probably write new puppet firewall rules.  Since the systems in question are all production servers, getting time for this is problematic as even a small mistake someplace on any one of the production servers could mean downtime that may or may not be readily apparent.

**Comment by davidschober** [comment]
That’s cool. So we’re setup as expected. We can close this then.

**Comment by Toputnal** [comment]
Fortunately, I knew this day would one day come, so we have a server in the managed-hosting environment that is classified as being a production server even though it isn't.  So, when we have time to work on this we do have at least one system to test on.  :-)

**Comment by davidschober** [comment]
Closing. Devops will kick off when ready.
