### ISSUE TITLE
puppetize imagemagick with openjpeg

### ISSUE THREAD

**Issue by davidschober** [nulib/images#140]

**Comment by davidschober** [comment]
@team is this still valid?

**Comment by davidschober** [comment]
@Toputnal this might be done. Can you verify. We're using it in production, but we're not sure if it was hot fixed by someone?

**Comment by davidschober** [comment]
per @Toputnal this is not being done in puppet.

**Comment by Toputnal** [comment]
@bmquinn Did you say there is some order of installing RPMs so that ImageMagick does not need to be custom compiled?  If so what was ith that you found?

**Comment by Toputnal** [comment]
I need to build a small test environment on devil.library to see which will be the best way to solve this issue.  Will update as I learn more.

**Comment by Toputnal** [comment]
Ok.  So.  Here's the deal.  The RHEL supported versions of ImageMagick don't have everything we need compiled in.  Fortunately, ImageMagick provides a .src.rpm which we can us to build our own versions.  I have ImageMagick rpm's compiling and am working on deciding how best to deploy these custom RPM's (there are custom RPM's on images-s and images-p based upon the ImageMagick.src.rpm from whatever date).  We can then add this package to puppet so that whenever we need to build an other Images box (or derivative thereof) an NUL-version of ImageMagic*.rpm will automatically be installed.  Since this is a core requirement of the Images project, it does seem to make sense to do this at least until such time as a sombody-else-supportable version of ImageMagick in .rpm format is available and which has the additional supported software libraries we need.

**Comment by davidschober** [comment]
@d-venckus will send @Toputnal what was done with IR.

**Comment by Toputnal** [comment]
I have the code and will implement it today.

**Comment by Toputnal** [comment]
Done for both images-s and images-p
