### ISSUE TITLE
libfedora3s needs deploy@images-s.library's public key for passwordless scp

### ISSUE THREAD

**Issue by davidschober** [nulib/images#161]

**Comment by davidschober** [comment]
There is a local directory on images-s per jim mounted per @Toputnal . Jim, can you add details?

**Comment by Toputnal** [comment]
Images-s is currently mounting the production share farchive13 at /mnt/farchive13.  I have created a symlink at /mnt/farchive that points to this location.  Once I get the NFS share setup in coordination with NUIT I will simply change the symlink to point at the new location, so that developers can simply reference /mnt/farchive and be done with it.  ☺

Best Regards,

--Jim

--
James R.  Bottino
Senior DevOps SysAdmin
Northwestern University Libraries
Northwestern University
www.library.northwestern.edu
james.bottino@northwestern.edu<mailto:james.bottino@northwestern.edu>
847-491-8389
