### ISSUE TITLE
Multiple version of Postgres on Menu-p. 8.4.20 should be uninstalled

### ISSUE THREAD

**Issue by kdid** [nulib/images#184]
Production is not working currently using old database

**Comment by kdid** [comment]
9.4 is the current one

**Comment by davidschober** [comment]
From SLACK: 9.4 is running now. 

JIM:
Cool. I see what the issue is.  menu-p is running on the super old puppetmaster server and the posgres puppet module for that version keep installing the postgres8.3 version.  Because of the work required I would suggest we make sure everything is A-OK on menu-s (which is on the newest PE server) and then schedule a migration of menu-p from puppetmaster to pe.library that may include downtime.  We can make a snapshot of the exis

**Comment by davidschober** [comment]
@d-venckus or @Toputnal can you give an update on this. We hammered out the oddness on staging, correct? So we should be able to snapshot and move?
