### ISSUE TITLE
make sure reboot script of postgres on menu-p boots up the right version

### ISSUE THREAD

**Issue by kdid** [nulib/images#185]
Production problem. 8.4 is old. 94 is current

**Comment by davidschober** [comment]
Emailed / etc the team. @Toputnal should be able it to grab it in the morning.

**Comment by Debs4Avalon** [comment]
Will it stop before the upgrade?

**Comment by Toputnal** [comment]
I'm trying to find a solution that will allow puppet to manage the most things it can, while still preserving the correct version of postgress.  So, it runs now, but if it were to be rebooted before I decide upon and implement a fix, the same issue will happen again.  Since menu-p is a production server, I'm working this until it is resolved and can be rebooted without manual intervention (for the postgreql version piece, at the very least).  B-)>

**Comment by Toputnal** [comment]
Ok.  I believe the postgress code in puppet is now working correctly on menu-s.

**Comment by Toputnal** [comment]
menu-p and menu-s both run the correct version of postgress, eg 9.4 across reboots, all done via puppet code.

**Comment by csyversen** [comment]
i'm marking this done. we don't want to reboot the servers yet to run through a full test because they are both in use, but if we run into issues in the future we'll just create another issue
