### ISSUE TITLE
permissions on "/var/www/menu/releases/"  are incorrect

### ISSUE THREAD

**Issue by csyversen** [nulib/images#212]
### Descriptive summary

Capistrano can't clear out old releases because "root" owns the public folder under each release, and cap runs as the deploy user

### Expected behavior

capistrano clears out old releases as needed without failing

### Actual behavior

it's failing

**Comment by d-venckus** [comment]
This behavior was being caused by Puppet, which was originally configured manage the /var/www/menu/current/public docroot folder in the vhost config, and would change ownership to root automatically.
I've added the directive manage_docroot=>false to the the vhost config for both menu-s and menu-p, and so Puppet will keep its greasy hands off the docroot folders and allow Capistrano to manage them.
