### ISSUE TITLE
move new puppet code to images-p, menu-p

### ISSUE THREAD

**Issue by davidschober** [nulib/images#229]
Move new puppet code to production servers. Ensure that servers can be rebooted and all services come up. 

- [x] images-p
- [x] menu-p

**Comment by Toputnal** [comment]
images-p will need to have scheduled downtime in order to migrate it from the puppet 2 server to the puppet 2016 server before it can receive any of the updated code we have running on images-s.  I estimate 4 hours of downtime for the migration.  Plus time to work out any issues we encounter after the migration.

**Comment by davidschober** [comment]
Nicole, can you schedule this?
