### ISSUE TITLE
have puppet restart fedora on libfedora3s

### ISSUE THREAD

**Issue by csyversen** [nulib/images#270]
### Descriptive summary

Let's have puppet ensure that staging fedora is running and restart it if it's not

Here's what David V said in slack: Yes, totally doable.  Puppet can just call "ensure=>running" on the service definition for tomcat-fedora.

**Comment by rtrautve1** [comment]
per conversation - a cron job does this now- be we want to change this to have puppet do this

**Comment by Toputnal** [comment]
I don't see the cron job being referred to here.  However, I do see that libsolr3s is NOT managed by puppet at all.  I'm writing the code for it and will migrate the server to PE so that it will have tomcat-fedora (and many other things) may be managed by puppet.  This may cause downtime @davidschober @csyversen @kdid  as I work on it.

**Comment by davidschober** [comment]
Awesome! Thanks @Toputnal

**Comment by csyversen** [comment]
@Toputnal @d-venckus i think you guys did this, right? If so, can we close this issue?

**Comment by carrickr** [comment]
20 days later and fedora appears to be running, so yeah it probably restarted.
