### ISSUE TITLE
When updating incorrect authorities the facets are not reindexing.

### ISSUE THREAD

**Issue by Nic4Images** [nulib/images#293]
### Search for bellange and you will see we have sets of 4 and 4 under Creator. They should merge into 8 under one authority after the edits but alas it is not happening.

 Include any relevant tracebacks if you're reporting a bug.
### Steps to reproduce the behavior
1. Choose any record on staging or production
2. Go to MENU and edit the Creator field then save
3. Go to Images and search for image, expand Creator facet to see old and incorrect and correct facets
### Is this related to the Work issue? We need to discuss it at Work record meeting @jenyoung scheduled.

Link to related tickets or prior related work here.

**Comment by Nic4Images** [comment]
![screen shot 2016-09-13 at 8 35 00 am](https://cloud.githubusercontent.com/assets/20801226/18475955/f1633914-798d-11e6-887c-2882e60b8dec.png)
![screen shot 2016-09-13 at 8 34 01 am](https://cloud.githubusercontent.com/assets/20801226/18475954/f163373e-798d-11e6-9a45-49c0ceaecc07.png)

**Comment by jenyoung** [comment]
test on staging. still happening?

**Comment by jenyoung** [comment]
this is still happening on staging and production. None of the facets are updating properly EXCEPT date. we hired a student to do some data cleanup for us in Images starting next week - some of which is based off the facets displaying in our public collections.  We would like of course all these changes to be reflected properly in our facets.

**Comment by davidschober** [comment]
dev team, can we do a small investigative dive?

**Comment by kdid** [comment]
@davidschober and @jenyoung 

In the example pictured above these are not the same character (you can see if you view source on the web page)

Compare:

```
https://images.library.northwestern.edu/catalog?f%5Bagent_name_facet%5D%5B%5D=Bellange%CC%81%2C+Hippolyte+%28French+painter+and+printmaker%2C+1800-1866%29&q=bellange
```

```
https://images.library.northwestern.edu/catalog?f%5Bagent_name_facet%5D%5B%5D=Bellang%C3%A9%2C+Hippolyte+%28French+painter+and+printmaker%2C+1800-1866%29&q=bellange
```

One is a regular "e" with an accent character added after and the other is an "accented e"

http://www.fileformat.info/info/unicode/char/0301/index.htm

http://www.fileformat.info/info/unicode/char/e9/index.htm

**Comment by jenyoung** [comment]
@kdid and @davidschober Right, we edited the agent set from one form to the other, correct form. In the bib records, the change is recorded, but it's not removing the old form in the facets.

**Comment by kdid** [comment]
@jenyoung, I don't follow what you mean by the bib record. When I check the VRA in fedora, the characters are different there as well. Can you elaborate?

**Comment by jenyoung** [comment]
I'm referring to the VRA

**Comment by kdid** [comment]
This is caused because though the VRA completely swapped with new values from menu, when the VRA is converted to solr, the new values are merged into the existing values in the solr doc rather than simply replacing them. 

This seems to be how all the vra description fields operate and have always operated, nothing specific to the agent_name_facet. 

I was able to change the behavior testing locally by changing line 506 in `vra_datastream.rb` to just use the new values in the facet rather than merging the two.

`solr_doc = solr_doc.merge(hashSet) { |field_name, oldval, newval|  oldval | newval }`

But, I think this needs a deeper dive to consider side effects and what might be involved in making this kind of change. There may be a reason why it works this way that is not immediately obvious.

**Comment by davidschober** [comment]
Awesome! Thanks Karen. Do you need help from anyone else digging into this?

**Comment by kdid** [comment]
@davidschober - Looking further, one complicating factor is that the code that creates the VRA and produces the solr docs is shared by both the image and VRAWork. So, that's why it was necessary to do the merge rather than the swap of the existing solr fields.

There is alot going on here with VRA coming from different sources -  menu ingesting, menu editing and batch and alot of complication with fields being juggled around and transformed to create the datastreams. 

This seems a fairly major design and architecture change plus refactoring  -- are we sure this type of change should be done here in Images rather than when we migrate to the NextGen repository?

At minimum, I think probably this needs a decision about how much time we want to put into this. It seems like a project rather than an issue.

**Comment by kdid** [comment]
@jenyoung and @davidschober - I think I have a workaround which avoids anything so drastic by just forcing a solr index update on the specific pid after a update. Let me know if that sounds good and I'll put it up on staging. You'll need to test/validate all the data fields as they would all potentially be affected.

**Comment by davidschober** [comment]
That sounds like a great plan @kdid.

**Comment by kdid** [comment]
@jenyoung you can go ahead and test this on staging. 

(Note that the Style Period facet changes in issue #294 are NOT included in this one...)

**Comment by jenyoung** [comment]
@kdid just tested on staging - all passes! yay!

**Comment by jenyoung** [comment]
reopening so we can remember to redeploy.
