### ISSUE TITLE
Multiple stylePeriods in a record not indexing properly in facets

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#294]
### Descriptive summary

 stylePeriod facet not indexing properly when there are multiple entries. Record display is good.
### Expected behavior

Each separate stylePeriod element should have a separate entry in the facets. 
### Actual behavior

They are in one line, separated by a semicolon. This is contrary to how we want the facets to work.

![2015-07-17_115012](https://cloud.githubusercontent.com/assets/2250501/18476027/25bb589a-798e-11e6-98b3-4f57fa1f1662.png)

**Comment by davidschober** [comment]
dev team, can we do a small investigative dive?

**Comment by kdid** [comment]
After investigating the code, it appears that this would be addressed by reversing this commit, which changed the Style/Period facet to be populated with the content of `<vra:stylePeriodSet><vra:display>` rather than the contents of each `<vra:stylePeriodSet><vra:stylePeriod>`.

https://github.com/nulib/images/commit/852324356827cf5ccd1e7332b7dee602934163fb

However, from the looks of things, if we do change that the Style/Period would have the same issue described in #293 (with the Creator facet), where if you edit a stylePeriod, it is added to what's already in the solr document rather than edited/replaced. (creating the situation where the facet contains both the old and the new values.)

Possibly this explains why the code was changed in this commit. 

Note also, if we do decide to do this, though the code change (if validated to work) may be minor, we should allow considerable time for testing and reindexing.

**Comment by davidschober** [comment]
let's hold until we think through #293

**Comment by kdid** [comment]
@jenyoung you can test this one on staging now as well. 
You'll probably want to test all ingest methods (menu edit, menu new record and batch) as they would all be affected. (This will not make retroactive changes to existing records automatically.)

**Comment by jenyoung** [comment]
@kdid tested. all good.
