### ISSUE TITLE
Cleanup ARCHV_IMG#location urls in production

### ISSUE THREAD

**Issue by bmquinn** [nulib/images#314]
These were broken out into the following separate issues. 
#322
#323
#324
#325
#326
#346

### Descriptive summary

ARCHV_IMG#location URLs are incorrect for possibly all images imported since they old synchronizer was shut down. There's going to be some data cleanup needed, and changes to our configs as well. #291 is blocked until this work is complete. There are possible tifs missing and permissions issues on the existing files to correct as well
### Expected behavior

ARCHV_IMG#location point to the correct URLs, and configs are correct going forward

**Comment by davidschober** [comment]
you beat me to it!

**Comment by davidschober** [comment]
This is scoped at Production only.

**Comment by kdid** [comment]
David, 
The scope of the cleanup is larger than initially thought. We should discuss. 

1. 1507 records have `http://repository.library.northwestern.edu/farchive/farchive13/inu-dil/hydra/images/` instead of `http://rstorage.library.northwestern.edu/farchive/farchive13/inu-dil/hydra/images/` as the base directory for ARCHV_IMG location
2. 23,724 have `http://www.library.northwestern.edu` - as the entire path - for ARCHV_IMG location
3. 3413 records have `repository.library.northwestern.edu/archive/farchive8` as the base url for ARCHV_IMG location (have not confirmed if this is wrong)
4. 477 records have nothing for ARCHV_IMG location.

**Comment by jenyoung** [comment]
This information came from Steve before he left. I had previously sorted it into what I thought were good categories using tabs. 

[badpids_all.xlsx](https://github.com/nulib/images/files/525646/badpids_all.xlsx)

**Comment by davidschober** [comment]
@kdid do you need @jenyoung to spot check metadata so we can close or are we goo to go?
