### ISSUE TITLE
~70,000 tifs not accessible at ARCHV_IMG location url due to permissions

### ISSUE THREAD

**Issue by kdid** [nulib/images#323]
Most of the images with ARCHV_IMG urls beginning with `http://rstorage.library.northwestern.edu/archive/farchive8` or`http://rstorage.library.northwestern.edu/archive/farchive13` are not accessible at that url due to permissions.

The exceptions to that are:
1. tif's with a timestamp in their filename. (We believe these are rescans)
2. Images where permissions were manually adjusted (World War II Collection) 
3. The most recent images which have been written in `archive/farchive13/inu-dil/hydra/images/`

Examples of inaccessible images:

```
curl -I http://rstorage.library.northwestern.edu/archive/farchive8/inu-dil/hydra/production/RealVMC/vmc07-3/9664/inu:dil-23da6ddc-47b4-4572-a69d-886f52dcd7e9.tif
HTTP/1.1 403 Forbidden
```

```
 curl -I http://rstorage.library.northwestern.edu/archive/farchive13/inu-dil/hydra/production/RealVMC/TESTS/Trans_Photo-Collection-Test/inu:dil-00ee2c8d-d7af-4971-9df4-b98cd0856ae6.tif
HTTP/1.1 403 Forbidden
```

Example of WWII tif:

```
curl -I http://rstorage.library.northwestern.edu/archive/farchive13/inu-dil/hydra/production/RealVMC/worldwar2posters/inu:dil-5f4c79ec-9f65-4e41-88aa-b4f1e128829b.tif
HTTP/1.1 200 OK
```

Example of (assumed) rescan

```
curl -I http://rstorage.library.northwestern.edu/archive/farchive8/inu-dil/hydra/production/RealVMC/vmc07-3/9664/inu:dil-23da6ddc-47b4-4572-a69d-886f52dcd7e9_2014-04-24_10:12:57.tif
HTTP/1.1 200 OK
```

This is related to (is part of) #314

**Comment by davidschober** [comment]
@Toputnal and @d-venckus can you verify that puppet isn't changing permissions on isilon shares (these).

**Comment by davidschober** [comment]
@Toputnal @d-venckus moving this to the top of ready. Can you look at it in thenext couple of days and let me know. All the tiffs should have the same permissions as the WWII images.

**Comment by Toputnal** [comment]
Looking...

**Comment by Toputnal** [comment]
Also, I should mention that I'm doubtful that puppet is doing anything here.  The only cases where puppet is managing permissions is the user/group permissions for the Images and Avalon dropboxes.  As I type this, davidschober, I seem to recall some point in the Images project, maybe Debs Cane remembers?, where there were duplicate files and the files were copied from one place to another because they were located in a directory named "test" or something like that.  The files were moved and the ownership changed to "deploy," IIRC, Jen L. was working on Images at the time, and I worked with her.  Are these the same files?

**Comment by davidschober** [comment]
@Toputnal Yes. I believe you and JL worked to move from /test to /production which I believe is the issue with #322. 

But these 70k seem to have permission issues. Can you check the permissions on a wwII image  PID 
inu:dil-5f4c79ec-9f65-4e41-88aa-b4f1e128829b

**Comment by Toputnal** [comment]
Is there a way to derive the path of the PID somehow?  I don't know what directory any particular PID is stored under.

**Comment by davidschober** [comment]
curl -I http://rstorage.library.northwestern.edu/archive/farchive13/inu-dil/hydra/production/RealVMC/worldwar2posters/inu:dil-5f4c79ec-9f65-4e41-88aa-b4f1e128829b.tif

**Comment by Toputnal** [comment]
I get 403 Forbidden on everything listed here. If this now works, can someone please let me know?  curl -I http://rstorage.library.northwestern.edu/archive/farchive8/inu-dil/hydra/production/RealVMC/vmc07-3/9664/inu:dil-23da6ddc-47b4-4572-a69d-886f52dcd7e9.tif

**Comment by davidschober** [comment]
@Toputnal That looks like one of the ones that needs to be fixed. The only one that was 200 was the WWII one. And I think you have to curl it from the repository server.

**Comment by Toputnal** [comment]
I believe the issue is with the "Other", of User/Group/Other fame, Read permissions.  The WWII posters are all set up with Other having Read permissions.  If I add Read permissions for Other to a file that does not work, it becomes visible.  I ran the following:

 on farchive13/inu-dil/hydra/production 
s find . -name "*.tif" -type f ! -perm /o+r | wc -l 
104907

on farchive8/inu-dil/hydra/production 
s find . -name "*.tif" -type f ! -perm /o+r | wc -l
29950

That's a total of: 134,857 files that are stored under the inu-dil/hydra/production directories on farchive8 and farchive13 that do not have Read permissions set for "Other".

As I don't know how our apps work, really, I don't know the level of security risk of making all these files read-accessible to Other...

**Comment by Toputnal** [comment]
I've kicked off the following command on farchive{8,13}/inu-dil:
 sudo find . -type f -name "*.tif" ! -perm o+r -print0 | sudo /usr/bin/xargs -I{} -0 chmod o+r {}
When that line finishes changing the permission for Other to Read, it would be great to run this test again.  I'll update here when  these runs finish.  --JRB

**Comment by davidschober** [comment]
@csyversen or @kdid can you do a spot check of these so we can close this issue?

**Comment by kdid** [comment]
Closing, I've spot checked, we'll know for certain when we implement the download feature and can open another issue then.
