### ISSUE TITLE
Try to mitigate performance issues by making users choose to use the zooming viewer

### ISSUE THREAD

**Issue by bmquinn** [nulib/images#383]
### Severity

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [ ] yes
- [x] no

### Descriptive summary

 Performance is bad enough on Images that I think using a standard sized image for the show views and making the openseadragon viewer accessible via a button click is the way to go.

**Comment by ccaizzi** [comment]
I just have to say, this is going to make all of us much happier.  Thanks for being proactive.

**Comment by kdid** [comment]
@ccaizzi, @Nic4Images and @jenyoung - 

We have this up on staging if you'd like to take a look and let us know. 

The landing page for each image contains one (600px high) image served by riiif. (This is as opposed to the viewer which makes about 10 calls just to load the initial view, and additional if you need to use the zoom or pan controls).  We put a button above the image in the button row to open the viewer in a new page for people who may still wish to use it. 

Since we don't have these initial images cached there would be longer page loads for the page the first time a page is viewed only. On staging, I'm seeing maybe 10 seconds for uncached images, (40 for the really big African maps). Production is beefier - so I was getting around 20 seconds to produce the image for the big African maps and less for more average sized images.

Let us know if we want to pursue this further.

It's possible we may be able to put a spinner on the image landing page if it seems like those loads are still a bit too long.

**Comment by davidschober** [comment]
Nice work. Thanks! I think a spinner is a good idea if only as a test for next gen.

**Comment by ccaizzi** [comment]
I'll let @Nic4Images weigh in, but I think this is a good direction.  And when you mean load, you mean just the first time someone loads the page, after that it is in cache for a year now meaning the next person to visit the image page will not have to wait that long, correct?

is there a usability reason we chose 600px high? it looks in alignment with other digital libraries like ucsd, but just curious. (see http://library.ucsd.edu/dc/search?f%5Bobject_type_sim%5D%5B%5D=image)

**Comment by kdid** [comment]
@ccaizzi, yes correct about the load. After the page loads once, the first time it's visited, the image would be cached for a year and the next person will not wait.

600 px high was what was set for the dimension of the image in the viewer but we can adjust.

**Comment by Nic4Images** [comment]
This sounds good to me. The curators I worked with this week are complaining about how awful Images is (unable to load images, search, etc.) so anything to make the performance better!

**Comment by Nic4Images** [comment]
I checked staging the the image size looks good.

**Comment by davidschober** [comment]
Zoom makes sense. Google just uses a magnifying glass.

**Comment by bmquinn** [comment]
Does this work? (Deployed this to staging so you can check it out)

<img width="670" alt="viewer_button" src="https://cloud.githubusercontent.com/assets/1395707/25258048/286472cc-2602-11e7-8aee-eed813488d14.png">

**Comment by Nic4Images** [comment]
BQ looks good to me!

**Comment by kdid** [comment]
@ccaizzi, @Nic4Images, @davidschober - Before we go live with this we just wanted to throw another option out there for consideration - the option of removing the zooming viewer completely. 

Right now we have simply hidden the problem from the initial view, but if a user clicks the button to zoom, we still will have load times of several minutes -  if at all - for uncached images. We fear if we leave it, there will still be the perception of a non-working application. 

If we remove the viewer, most users would still have the option to zoom the displayed image with the browser's zoom tool or to download a 1600px jpg image. Not sure if that still meets the requirements for power users but if the zooming viewer still seems broken to users we might not be meeting the requirements anyways. 

We understand if it's not an option, just wanted to throw it out there since we hadn't heard it mentioned.

**Comment by Nic4Images** [comment]
I would want to speak with our power users before we removed it. Aka the curators. They may not care since all I hear are complaints about Images as of late. But I do not like removing functionality before checking in with the people using Images. This would take me until Monday since it is late on Friday.

**Comment by Nic4Images** [comment]
If you want me to gather feedback let me know before 5PM today so I have time to find curators.

**Comment by kdid** [comment]
@Nic4Images - we trust your judgement on whether to get feedback on this. Just let us know when you decide. We're not deploying the update until next week in either case as there is a few things we need to do alongside deployment that we are not quite ready with.

**Comment by ccaizzi** [comment]
My two cents--some of our content is very detailed and the zoom is needed to analyze it (those african maps for example--even the smaller images like the postcards and it loads fine for me now). But if the zoom will not load in a timeframe most users are willing to wait and we decide to remove the feature all together, then I suggest we make a larger JPG than 1600 pixels (isn't 1980 the common size now?) and push up the static display image a bit as well.   And can we be sure to write a story about creating the infrastructure to support zoom for our beautiful images in nextgen?

**Comment by davidschober** [comment]
Are we seeing several minutes on al I cached images it just African maps? Let's talk when I get back.

**Comment by kdid** [comment]
@ccaizzi - just to clarify, the button for the JPG ("Download Small Image (JPG)") calls an image 1600 px high, with width variable, so the image often is wider than 1600. For example (2300 x 1600): http://images.library.northwestern.edu/image-service/inu-dil-08699050-fa07-4207-ab06-a7e93ff5b928/full/,1600/0/default.jpg

@davidschober - no, not African maps. Still working on trying to cache those. The images Nicole couldn't get to load last week were La Caricature images.

**Comment by ccaizzi** [comment]
@kdid thx, that helps--i thought it was the width, not the height.  so keeping the same sounds fine to me.

i still vote for keeping the zoom image button--the static image helps a ton in terms of frustration.  some of our images do zoom nicely.

**Comment by Nic4Images** [comment]
We need to keep the zoom button. I checked with a faculty member and curator. They both appreciate that option.

**Comment by davidschober** [comment]
The only other option I would throw out is for the "open in image viewer" to go full screen (e.g. what happens when you hit the full-screen option on the zoomable viewer). If that's not straight forward, we can leave as is.

**Comment by davidschober** [comment]
abandoned.
