### ISSUE TITLE
Test tif with very large images

### ISSUE THREAD

**Issue by davidschober** [nulib/images#384]
We have a couple of very-large image collections. We are going to test manually converting those tit tif and see how riiif responds. 

TODO:

- [x] convert maps in images-s to tif
- [x] clear cache and see how riiif performs
- [x] if performance gain is not great, consider resizing to 10k x 10k

**Comment by carrickr** [comment]
So we initially tried on `images-s` and found that when working with uncached images and using my internet at home (10 mbps down, not the fast campus stuff):

* Loading a large .jp2 Map of Africa took ~6 to 8 minutes depending on the size
* Converting it to tiff lead to load times of under one minute for anything under 200 mb and 12k x 12k.  Sizes over 12k x 12k would push 500 mb and take up to 4 minutes for all the tiles to generate and load

On `images-p` we were unable to large .jp2s.  Karen could see the the convert processes die in console and on the end user side I could see the 500 errors appear in my javascript console. Converting these .jp2s to .tiffs resulted in load times under one minute, even for very large files (ex: 15k x 14k at 570 mb).  

The theory is that production has 16 cores and thus can handle more simultaneous tile convert requests than staging.  A 15k x 14k image would need few tiles than we have CPU cores, whereas it would need to queue converting tiles on staging.  Whereas at 10k x 10k on staging, you have more cores than you need tiles.  So each convert command gets its own core, no waiting.

So of course the question is if under heavy load (multiple users all requesting different very large images that aren't cached at the same time) if we'd start to see longer wait times since you'd have significantly more convert commands than tiles.  Although images-p might not get that load, especially since aside from a few collections most of the images are much smaller and would spawn fewer commands.

Anyway for a path forward it seems to be:

* Request more disk space for `/dlun1/dimages/`, probably about 20 terabytes
* Convert/Replace all the .jp2s to .tiffs
* Do something with the .jp2s

The open questions are:

* Do we obtain our presentation tiffs via converting the jp2s, or look through `isilon1.ci.northwestern.edu:/ifs/data/Library/repository/farchive13` to find them and then move them in?  Converting them takes more disk space and CPU time, but doesn't touch our preservation copy tiffs.  Conversely if we pull the tiffs from `farchive13` we use less disk space by not duplicating them.  However if we later we need to downsize to 10k x 10 k or smaller on production, we'd need to be sure to archive a copy of the full size master.
* Do we save the .jp2s or delete them?  Saving them would save us time later if we did a proper .jp2 server as part of next gen, but we could also just regenerate them from the .tiffs

**Comment by davidschober** [comment]
If we run into getting bashed by multiple users we might want to run in single-core mode. The jp2 convert was seriously processor intensive.

**Comment by carrickr** [comment]
Personal thoughts:

* Make our own 'alterable' tiffs from the 'jp2s'.  It's less programmer time than having a programmer hunt through the `farchive13` directory and match up original tiffs to jp2s and copying them over.  We can just do a script along the lines of:
```
Parallel.map(Dir["/dlun1/dimages/*.jp2"], in_threads: 8).do |image|
   new_image = image.sub! '.jp2','.tiff'
   exec(convert image, new_image)
   FileUtils.rm image or FileUtils.m image new_place
end
```

This would run 8 convert commands at the same time, since convert seems single threaded in our tests and just blow down the directory.  With of course some logging and error checking added to the script.  Run that over the weekend or something and aim to come in to work on Monday with all .tiffs.

Then in the future if we need to resize downwards due to performance we can do that without needing to worrying about backing up the original, etc.  We know that anything in this directory is mutable.  

As for keeping the .jp2s, I'm not too attached to them.  Future ingested items won't have them and I'd rather just do a totally clean creation of them come NextGen if/when we have an image server that wants them.

**Comment by davidschober** [comment]
Is convert still running single threaded because we set it that way? It was eating up everything. Did David  V. need to restart?

**Comment by kdid** [comment]
@carrickr is talking about converting jp2s to tifs, @davidschober you are talking about converting the jp2s by riiif for the viewer. The variable was only changed on staging and he did change it back and restart today.

**Comment by carrickr** [comment]
@davidschober I'm referencing when I just manually run `convert` via the command line to go jp2 to tiff.  I don't know if dev-ops set it that way or not, but that's the behavior I'm seeing.  Single threaded and takes 2 to 3 minutes for a large file.

**Comment by davidschober** [comment]
Right, but it’s calling the same convert right?

**Comment by carrickr** [comment]
@davidschober Yes, but riif calls it numerous times, like a convert per tile or something, so it was probably set to single threaded due to the number of threads spawned

**Comment by davidschober** [comment]
closing this. We have moved forward with the plan.
