### ISSUE TITLE
Regression testing images (VRA works, tiffs)

### ISSUE THREAD

**Issue by davidschober** [nulib/images#398]
## Description

The dev team has made improvements to the images looking to ensure that the speed of the system is acceptable as we work on the next generation repository.

Of note:

* VRA works have been abandoned #396
* We are no longer creating or displaying jp2s #386 #393 #395

## Please pay special attention to

- ingestion (batch, etc)
- creation of metadata
- publishing
- display of images

This will require a full regression test. 

[Test Images Staging](https://docs.google.com/spreadsheets/d/19zRjEh5roYUIBFGyKf0YIx4xNfkPp_NCNndDLnHUmYk/edit#gid=2053022108)

[Test Menu Staging](https://docs.google.com/spreadsheets/d/12Px9VSe1ThmSPhN51LAWAAg0PSuaf0hcDvyHa6fzGwI/edit#gid=0)

Please formally sign off with this issue. 

@csyversen let Jen know when her team can go.

**Comment by csyversen** [comment]
here are the release notes i came up with: 

we now produce derivative tiff images from the original archival quality tiff
  - this should speed up both derivative creation (from both menu and batch) as well as image delivery when viewing images from the website

we no longer produce VRAWork objects in Fedora. They contained the same information as the VRAImage record and only served to make development harder
  - this will slightly speed up object creation and retrieval since there are fewer calls to fedora
  - the existing vrawork objects will still exist in our Fedora instance for now, but the application will no longer update or acknowledge them. We can always clean/remove them later

we reduced the number of concurrent threads during batch processing
  - previously doing batch imports would consume all resources on the server and render it unresponsive. We reduced the concurrent running threads to just one. This allows batches to continue to work while the server remains responsive for regular use

we cleaned up our ldap integration

some under the hood maintenance
  - updated ruby
  - updated several dependent gems, including riiif
  - various code cleanup in several classes and modules

**Comment by egilchrist** [comment]
I tested Menu and Images on staging.  Everything worked as it's supposed to - no issues.  The metadata published successfully.  The images and thumbnails seemed to load much faster than they previously did (my images were maps and caricatures).

**Comment by jenyoung** [comment]
Finished the last bit of testing an institutional collection. All works great and fast!

**Comment by csyversen** [comment]
Awesome, that's good to hear! Thanks for testing, it sounds like we're ready to push to production. @Nic4Images @jenyoung can we do it this week? Do you have any time in mind?

**Comment by jenyoung** [comment]
@csyversen we are spending a lot of the week on AVR. perhaps Thursday or Friday?

**Comment by csyversen** [comment]
@jenyoung sounds good. I'm out on Friday, but hopefully things work out for Thursday!

**Comment by jenyoung** [comment]
@csyversen after talking over with @ccaizzi and looking at the calendar, it's currently finals. we want to finals are over just in case someone is using it. also, my temp is here mon-thurs-fri and she only works on the army hospital project. i don't have anything else for her to do for several hours. so -- how about next tuesday the 13th? we should also put up a notice that the system will be down on the front page.

**Comment by csyversen** [comment]
Good call, I can put up the notice today. I can just put up a simple notice like "The Images application will undergo maintenance on Tuesday 13th from 9am - 11am. The application will be unavailable during this time" 

sound good? @jenyoung @ccaizzi

**Comment by ccaizzi** [comment]
@csyversen great, and yes, that is great except call it the "Repository | Images website"   The "website" will be unavailable...

**Comment by jenyoung** [comment]
Tuesday June 13th - and what Carolyn said. We'll wait for the go ahead from you to test Tuesday afternoon then. @egilchrist  note we'll be testing on production.

**Comment by csyversen** [comment]
(i'm going to create a new issue for deploying to prod and putting the text up there)
