### ISSUE TITLE
Linrothe collections jobs for migration

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#425]
for purposes of migration, would be helpful to have a list of the Linrothe jobs belonging to each collection.

Get a list from @Nic4Images if possible of the jobs for both Linrothe collections and make sure they are in the right ones for migration.

**Comment by davidschober** [comment]
Jen, I'm not sure who's work this is, can you write it up in a bit more detail?

**Comment by Nic4Images** [comment]
@jenyoung - Since these were cataloged in Voyager / ARTDB and before SmartSheet existed - I think the only way to "get them" is to go through item level records in Images, or dig into the Excel spreadsheet Dan exported from G Docs. I cannot promise 100% sound data on either fronts .. Thinking about this some more I would run them against the spreadsheet ARTstor sent us in that export from years ago.

**Comment by jenyoung** [comment]
Thanks @Nic4Images - I figure now would be a good time to do a sweep and cleanup anything during the migration.

**Comment by Nic4Images** [comment]
@jenyoung to be clear you want this to match old job#s against what is in Images? Otherwise matching the 5,035 images currently in his pub coll against the new one post migration seems fine enough to me. 5,035 is the final number right now.

**Comment by Nic4Images** [comment]
Here are all of the legacy Job#'s from our old tracking system 
[vmc-2014-jan9LINROTHE.xlsx](https://github.com/nulib/images/files/2005878/vmc-2014-jan9LINROTHE.xlsx)
